### ISSUE TITLE
Minimum Python version should be set to 3.9

### ISSUE THREAD

**Issue by peteeckel** [commonism/netbox-webhook#1]
For some reasons, my default build/test environment for NetBox DNS runs Python 3.8 (it's always better not to have features that only higher supported Python versions provide when developing).

netbox-webhook installs on Python 3.8 just fine, but then refuses to work because `typing` does not have the `Annotated` class in Python 3.8. With Python 3.9+ it's fine.

**Comment by peteeckel** [comment]
Probably 3.9 isn't sufficient either, though this might be fixable:
```
(wbh39) [vagrant@webhook netbox-webhook]$ python3 -m uvicorn netbox_webhook.netbox:app --reload --port 8053 --host 0.0.0.0
INFO:     Will watch for changes in these directories: ['/vagrant/netbox-webhook']
INFO:     Uvicorn running on http://0.0.0.0:8053 (Press CTRL+C to quit)
INFO:     Started reloader process [6830] using StatReload
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/usr/lib64/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib64/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/vagrant/netbox-webhook/wbh39/lib64/python3.9/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/vagrant/netbox-webhook/wbh39/lib64/python3.9/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib64/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/vagrant/netbox-webhook/wbh39/lib64/python3.9/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/vagrant/netbox-webhook/wbh39/lib64/python3.9/site-packages/uvicorn/config.py", line 467, in load
    self.loaded_app = import_from_string(self.app)
  File "/vagrant/netbox-webhook/wbh39/lib64/python3.9/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/vagrant/netbox-webhook/netbox_webhook/netbox.py", line 6, in <module>
    from . import models
  File "/vagrant/netbox-webhook/netbox_webhook/models.py", line 61, in <module>
    class _Snapshots(BaseModel, Generic[EventTypeRequestT]):
  File "/vagrant/netbox-webhook/netbox_webhook/models.py", line 62, in _Snapshots
    prechange: EventTypeRequestT | None
TypeError: unsupported operand type(s) for |: 'TypeVar' and 'NoneType'
```
The reloader process then runs forever without opening any ports.

Python 3.11 does not have this issue, so I'll continue with 3.11.

**Comment by commonism** [comment]
It works with 3.8 when adding typing_extensions workarounds - I'll go that route
`| None` can be written as Optional[] as well.
